name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure node
        uses: ./.github/workflows/actions/setup-project

      - name: Run tests
        run: npm test

      - name: Build app
        run: npm run build

      - name: Deploy app to Vercel production env
        uses: ./.github/workflows/actions/deploy-vercel
        with:
          mode: production
          vercel-token: ${{ secrets.VERCEL_AUTH_TOKEN }}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORGANIZATION_ID: ${{ secrets.VERCEL_ORGANIZATION_ID }}
